from snakemake.utils import min_version
from pathlib import Path

##### set minimum snakemake version #####
min_version("8.4.1")

configfile: "config/config.yaml"

include: "rules/common.smk"

rule all:
    input:
        expand(
            ws_path("ld/chr{chrom}"),
            chrom=[i for i in range(1,23)],
        ),
        expand(
            ws_path("{seqid}/seq.{seqid}.gwaslab.P.tsv"),
            seqid=analytes.seqid,
        )

rule compute_ld:
    input:
        get_inputs()
    output:
        ws_path("ld/chr{chrom}"),
    params:
        bfile = get_inputs_stem(),
        ld_window = config.get('ldsc_dict').get('window')
    conda:
        "envs/ldsc.yml"
    resources:
        runtime= lambda wc,attempt: attempt * 60,
    shell:
        """
    ldsc.py \
    --out {output} \
    --bfile {params.bfile} \
    --l2 \
    --ld-window-kb {params.ld_window} """

# rule make_list:
#     input:
#         config.get("path_seqids"),
#     output:
#         config.get("path_seqids"),
#     params:
#         sum_stats = config.get("path_sumstats"),
#         suffix = config.get("suffix"),
#     shell:
#         """
#     find {params.sumstats} -name {params.suffix} > {output}
# """

rule append_pvalue:
    input:
        sumstats_path(),
    output:
        ws_path("{seqid}/seq.{seqid}.gwaslab.P.tsv")
    shell:
        """
        zcat {input} | \
        awk 'BEGIN{{OFS="\t"}} {{print $0, (NR==1 ? "P" : 10^-($13))}}' > {output}
"""
